name: handful_of_trials
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2018.03.07
  - certifi=2018.8.24
  - cffi=1.11.5
  - intel-openmp=2019.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgfortran=3.0.1
  - mkl=2018.0.3
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - ncurses=6.1
  - ninja=1.8.2
  - numpy-base=1.15.2
  - openssl=1.0.2p
  - pycparser=2.19
  - python=3.5.6
  - pytorch=1.0.0
  - readline=7.0
  - setuptools=40.2.0
  - sqlite=3.25.3
  - tk=8.6.8
  - wheel=0.31.1
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - absl-py==0.6.1
    - appnope==0.1.0
    - astor==0.7.1
    - atomicwrites==1.2.1
    - attrs==18.2.0
    - backcall==0.1.0
    - chardet==3.0.4
    - cycler==0.10.0
    - cython==0.29.2
    - decorator==4.3.0
    - dotmap==1.2.20
    - future==0.16.0
    - gast==0.2.0
    - gitdb2==2.0.5
    - gitpython==2.1.11
    - gpflow==1.3.0
    - grpcio==1.17.1
    - gym==0.9.4
    - h5py==2.8.0
    - idna==2.8
    - ipython==7.2.0
    - ipython-genutils==0.2.0
    - jedi==0.13.2
    - keras-applications==1.0.6
    - keras-preprocessing==1.0.5
    - kiwisolver==1.0.1
    - line-profiler==2.1.2
    - markdown==3.0.1
    - matplotlib==3.0.2
    - more-itertools==4.3.0
    - mujoco-py==0.5.7
    - multipledispatch==0.6.0
    - numpy==1.14.0
    - pandas==0.23.4
    - parso==0.3.1
    - pathlib2==2.3.3
    - pexpect==4.6.0
    - pickleshare==0.7.5
    - pip==18.1
    - pluggy==0.8.0
    - prompt-toolkit==2.0.7
    - protobuf==3.6.1
    - ptyprocess==0.6.0
    - py==1.7.0
    - pyglet==1.3.2
    - pygments==2.3.1
    - pyopengl==3.1.0
    - pyparsing==2.3.0
    - pytest==4.0.2
    - python-dateutil==2.7.5
    - pytz==2018.7
    - requests==2.21.0
    - scipy==0.19.0
    - six==1.12.0
    - smmap2==2.0.5
    - tensorboard==1.12.1
    - tensorflow==1.12.0
    - termcolor==1.1.0
    - tqdm==4.19.4
    - traitlets==4.3.2
    - urllib3==1.24.1
    - wcwidth==0.1.7
    - werkzeug==0.14.1
prefix: /Users/QV/miniconda3/envs/handful_of_trials

